server:
  port: 8051

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_service_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: default



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true



springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


logging:
  level:
    root: INFO
  file:
    name: app.log

#eureka config
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true


