server:
  port: 7000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8052/api/students
          predicates:
            - Path=/api/students/**

        - id: course-service
          uri: http://localhost:8051/api/courses
          predicates:
            - Path=/api/courses/**

        - id: enrollment-service
          uri: http://localhost:8053/api/enrollments
          predicates:
            - Path=/api/enrollments/**
